[package]
name = "yaww"
version = "0.1.0"
authors = ["not_a_seagull <jtnunley01@gmail.com>"]
edition = "2018"

[dependencies]
bitflags = "1.2.1"
event-listener = "2.5.1"
flume = { version = "0.10.1", default-features = false }
futures-lite = { version = "1.11.3", optional = true }
gluten-keyboard = "0.1.2"
log = "0.4"

[dependencies.winapi]
version = "0.3.9"
features = ["impl-debug", "errhandlingapi", "libloaderapi", "minwindef", "ntdef", "processthreadsapi", "winbase", "windef", "winuser"]

[dev-dependencies]
async-executor = "1.4.0"
async-io = "1.3.1"
easy-parallel = "3.1.0"
env_logger = { version = "0.8.2", default-features = false, features = ["atty", "termcolor"] }

[features]
async = ["flume/async", "futures-lite"]
