[package]
name = "yaww"
version = "0.1.0"
authors = ["not_a_seagull <jtnunley01@gmail.com>"]
edition = "2018"

[dependencies]
bitflags = "1.2.1"
flume = { version = "0.10", default-features = false }
log = "0.4"
parking = "2"

[dependencies.winapi]
version = "0.3"
features = ["errhandlingapi", "minwindef", "processthreadsapi", "winbase", "wingdi", "winuser"]

[features]
default = []
async = ["flume/async"]
