[directives]
modules = [
    'Windows.Win32.Foundation',
    'Windows.Win32.System.Registry',
    'Windows.Win32.Graphics.Gdi',
    'Windows.Win32.UI.Input.Pointer',
    'Windows.Win32.UI.Controls',
    'Windows.Win32.UI.Shell',
    'Windows.Win32.UI.WindowsAndMessaging',
    'Windows.Win32.System.LibraryLoader',
    'Windows.Win32.Graphics.OpenGL',
]
ignore = [
    "LPFNDFMCALLBACK",
    "LPFNADDPROPSHEETPAGES",
    "ABORTPATH",
    "Assoc*",
    "BANDINFOSFB",
    "*BROWSE*",
    "CDef*",
    "CIDL*",
    "CONFIRM_CONFLICT_ITEM",
    "ConnectToConnectionPoint",
    "DECIMAL",
    "DETAILSINFO",
    "*ImageList*",
    "Hlink*",
    "IUnknown_*",
    "GetDpiForShell*",
    "NC_ADDRESS",
    "NRESARRAY",
    "NT_CONSOLE_PROPS",
    "PERSIST_FOLDER_*",
    "ShellExecuteEx*",
    "RegisterDeviceNotification*",
    "SHARD*",
    "SHAn*",
    "SFV_*",
    "SHCo*",
    "SHCO*",
    "SHCh*",
    "SHCr*",
    "SHCR*",
    "SHDe*",
    "SHEn*",
    "SHEv*",
    "SHGe*",
    "SHPa*",
    "SHQu*",
    "SHFo*",
    "SHFI*",
    "SHFi*",
    "SHNA*",
    "SHLo*",
    "SHRe*",
    "SHSe*",
    "SHOp*",
    "SHS*",
    "SHQU*",
    "SHFO*",
    "SMCSH*",
    "SHDR*",
    "SHDE*",
    "SORT*",
    "SHUn*",
    "SHUp*",
    "SHVa*",
    "SYNCMGR*",
    "WINDOWDATA",
    "Reg*Key*",
    "Path*",
    "Url*",
    "URL*",
    "*printf*",
    "*Char*",
    "Mrm*",
    "InSendMessageEx",
    "Reg*",
    "FindExecutable*",
    "Str*",
    "ExtractAssociatedIcon*",
    "GetCurrentProcess*",
    "*COMBOBOXEX*",
    "APPCATEGORY*",
    "CBT_*",
    "*CCI*",
    "NMHEADER*",
    "REDIRECTION*",
    "TASKDIALOG*",
    "TaskDialog*",
    "PROPSHEET*",
    "*PSPCALLBACK*",
    "*PropertySheet*",
    "SHELL*",
    "INPUT_TRANS*",
    "*InputTransform*",
    "Sys*",
    "GetTheme*",
    "CreateProfile",
    "NMT*",
    "NMB*",
    "gl*",
    "EnumMetaFile",
    "TV*",
    "GetOutlineTextMetrics*",
    "HMONITOR_User*arshal*",
    "GetBufferedPaintBits",
    "UnregisterApp*",
    "Shell_NotifyIcon*",
    "CommandLine*",
    "GCP_*",
    "AXESLIST*",
    "AXISINFO*",
    "CATEGORY_*",
    "*CCSTYLE*",
    "CCCOLUMN*",
    "CMCOLUMN*",
    "DESKBAND*",
    "CREDENTIAL_*",
    "ENUMUILANG",
    "DoEnvironment*",
]
actual_bools = [
    "*_visible*",
    "*_in_*",
    "in_*",
    "*is_*",
    "equal_*",
    "translate_message",
]
dont_merge = [
    "cchText",
    "c*Desired",
    "nIDEvent",
    "cWidth",
    "cchMax*Name",
]
stub_struct = [
    "DEVMODE*",
]

[real_arr_type]
CM_COLUMNINFO = { fname = "wszName", real_ty = "u16" }
DISPLAY_DEVICEW = { fname = "Device*", real_ty = "u16" }
DROPDESCRIPTION = { fname = "sz*", real_ty = "u16" }
ENUMLOGFONTW = { fname = "elf*", real_ty = "u16" }
ENUMLOGFONTEXW = { fname = "elf*", real_ty = "u16" }
EXTLOGFONTW = { fname = "elf*", real_ty = "u16" }
FILEDESCRIPTORW = { fname = "cF*", real_ty = "u16" }
LOGFONTW = { fname = "lf*", real_ty = "u16" }
EXP_DARWIN_LINK = { fname = "szw*", real_ty = "u16" }