[directives]
modules = [
    'Windows.Win32.Foundation',
    'Windows.Win32.System.Registry',
    'Windows.Win32.Graphics.Gdi',
    'Windows.Win32.UI.Input.Pointer',
    'Windows.Win32.UI.Controls',
    'Windows.Win32.UI.Shell',
    'Windows.Win32.UI.WindowsAndMessaging',
    'Windows.Win32.System.LibraryLoader'
]
ignore = [
    "LPFNDFMCALLBACK",
    "LPFNADDPROPSHEETPAGES",
    "ABORTPATH",
    "Assoc*",
    "BANDINFOSFB",
    "*BROWSE*",
    "CDef*",
    "CIDL*",
    "CONFIRM_CONFLICT_ITEM",
    "ConnectToConnectionPoint",
    "DECIMAL",
    "DETAILSINFO",
    "*ImageList*",
    "Hlink*",
    "IUnknown_*",
    "GetDpiForShell*",
    "NC_ADDRESS",
    "NRESARRAY",
    "NT_CONSOLE_PROPS",
    "PERSIST_FOLDER_*",
    "ShellExecuteEx*",
    "RegisterDeviceNotification*",
    "SHARD*",
    "SFV_*",
    "SHCo*",
    "SHCO*",
    "SHCh*",
    "SHCr*",
    "SHCR*",
    "SHDe*",
    "SHEn*",
    "SHGe*",
    "SHPa*",
    "SHQu*",
    "SHRe*",
    "SHSe*",
    "SMCSH*",
    "SORT*",
    "SYNCMGR*",
    "WINDOWDATA",
    "Reg*Key*",
]