[directives]
modules = [
    'Windows.Win32.Foundation',
    'Windows.Win32.System.Registry',
    'Windows.Win32.Graphics.Gdi',
    'Windows.Win32.UI.Input.Pointer',
    'Windows.Win32.UI.Controls',
    'Windows.Win32.UI.Shell',
    'Windows.Win32.UI.WindowsAndMessaging',
    'Windows.Win32.System.LibraryLoader'
]
ignore = [
    "LPFNDFMCALLBACK",
    "LPFNADDPROPSHEETPAGES",
    "ABORTPATH",
    "Assoc*",
    "BANDINFOSFB",
    "*BROWSE*",
    "CDef*",
    "CIDL*",
    "CONFIRM_CONFLICT_ITEM",
    "ConnectToConnectionPoint",
    "DECIMAL",
    "DETAILSINFO",
    "*ImageList*",
    "Hlink*",
    "IUnknown_*",
    "GetDpiForShell*",
    "NC_ADDRESS",
    "NRESARRAY",
    "NT_CONSOLE_PROPS",
    "PERSIST_FOLDER_*",
    "ShellExecuteEx*",
    "RegisterDeviceNotification*",
    "SHARD*",
    "SFV_*",
    "SHCo*",
    "SHCO*",
    "SHCh*",
    "SHCr*",
    "SHCR*",
    "SHDe*",
    "SHEn*",
    "SHEv*",
    "SHGe*",
    "SHPa*",
    "SHQu*",
    "SHFI*",
    "SHFi*",
    "SHNA*",
    "SHRe*",
    "SHSe*",
    "SHOp*",
    "SHS*",
    "SHQU*",
    "SHFO*",
    "SMCSH*",
    "SHDR*",
    "SHDE*",
    "SORT*",
    "SYNCMGR*",
    "WINDOWDATA",
    "Reg*Key*",
    "Path*",
    "Url*",
    "URL*",
    "*printf*",
    "*Char*",
    "Mrm*",
    "InSendMessageEx",
    "Reg*",
    "FindExecutable*",
    "Str*",
    "ExtractAssociatedIcon*",
    "GetCurrentProcess*",
    "*COMBOBOXEX*",
    "APPCATEGORY*",
    "CBT_*",
    "*CCI*",
    "NMHEADER*",
    "REDIRECTION*",
    "TASKDIALOG*",
    "TaskDialog*",
    "PROPSHEET*",
    "*PSPCALLBACK*",
    "*PropertySheet*",
    "SHELL*",
    "INPUT_TRANS*",
    "*InputTransform*",
    "Sys*",
]
actual_bools = [
    "*_visible*",
    "*_in_*",
    "in_*",
    "*is_*",
]